### ISSUE TITLE
ios13 移除通知崩溃，求解决！

### ISSUE THREAD

**Issue by goodMrs** [changsanjiang/SJObserverHelper#1]
每次退出页面，都会崩溃到__SJKVOObserver中的delloc中的移除KVO里面，看了半天不知道如何解决，希望楼主帮忙谢谢了！

**Comment by changsanjiang** [comment]
提供一下堆栈吧, 我看看

**Comment by goodMrs** [comment]
self	__SJKVOObserver *	0x28276f480	0x000000028276f480
_target	AVPlayerLayer *	0x2829e4020	0x00000002829e4020
_keyPath	__NSCFConstantString *	@"readyForDisplay"	0x000000010616dd80
_hanlder	SJKVOObservedChangeHandler	0x00000001061321bc

**Comment by goodMrs** [comment]
Thread 1: EXC_BAD_ACCESS (code=1, address=0x656565656565668d)

**Comment by changsanjiang** [comment]
看看这个 [issue](https://github.com/changsanjiang/SJVideoPlayer/issues/153) 吧, 替换一下
